export const ADD_STUDENT = "ADD_STUDENT";
export const DISPLAY_STUDENT = "DISPLAY_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

// import {ADD_STUDENT,DISPLAY_STUDENT,DELETE_STUDENT} from './store/constant';
